version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: telemetry
      POSTGRES_USER: telemetry_user
      POSTGRES_PASSWORD: telemetry_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  telemetry-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://telemetry_user:telemetry_password@postgres:5432/telemetry?sslmode=disable
      LOG_LEVEL: info
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
